[package]
name = "diff-derive"
version = "0.1.0"
authors = ["BenHall-7 <benjaminjahall@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = [ "full" ] }
proc-macro2 = "1"
quote = "1"